# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 846968a83884bb49f9c0c55f4dbf24d1715039ebcbbe4e8dc2518cd5abaa58cdecfa65675715e02fa60c1aa819cccf91305c301995ed35b2f87134eff37a36b5

test:
  secret_key_base: 4ba127ec0c1a7966065a5000e4c4b626d3909242e4327fbd85e28fd3d1f4b4b4408959e463b01e295a67de5b5b0755210dce747ef7f8b663ab88afe958241d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
